# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MSP
email: mspal@ucdavis.edu
description: > # this means to ignore newlines until "baseurl:"
  I am a second year student at the University of the California, Davis pursuing
  a double major in Design and Computer Science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://minupalaniappan.com" # the base hostname & protocol for your site
twitter_username: minupalaniappan
github_username:  minupalaniappan

# Build settings
markdown: kramdown
